In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.7.0-cp312-cp312-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\rebal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\rebal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.14.1)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.0-cp312-cp312-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ------------- -------------------------- 3.7/10.7 MB 21.7 MB/s eta 0:00:01
   ----------------- ---------------------- 4.7/10.7 MB 12.4 MB/s eta 0:00:01
   --------------------- ------------------ 5.8/10.7 MB 10.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.6/10.7 MB 8.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.6/10.7 MB 7.8 MB/s eta 0:00:01
   ------------------------------ --------- 8.1/10.7 MB 7.2 MB/s eta 0:00:01
   ------------------------------- -------- 8.4/10.7 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.7 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.7 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.0/10.7 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 4.7 MB/s eta 0:00:00
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.5.1 scikit-learn-1.7.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\rebal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [11]:
pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\lib\site-packages (25.0.1)
Collecting pip
  Downloading pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-25.1.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 20.0 MB/s eta 0:00:00
Installing collected packages: pip
Successfully installed pip-25.1.1
Note: you may need to restart the kernel to use updated packages.

In [20]:
df = pd.read_csv(r"boston_original_dataset.csv")

In [23]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
4,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
502,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
503,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
504,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
505,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6

In [22]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [28]:
# independent features and dependent feature
x = df 
y= df["MEDV"]
t_y = np.array(y)
t_y

array([24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6,
       34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. ,
       21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7,
       24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6, 34.7, 24. , 21.6])

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, t_y, test_size=0.30, random_state=42)

In [31]:
x_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
5,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
116,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
45,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
16,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
468,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
270,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
348,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
435,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
102,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0

In [32]:
## standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [34]:
from sklearn.linear_model import LinearRegression
# cross validation
from sklearn.model_selection import cross_val_score

In [35]:
regressor = LinearRegression()

In [ ]:
cross_val = cross_val_score(regressor, x_train, y_train,scoring='neg_mean_squared_error', cv=5)

In [38]:
np.mean(cross_val)

-1.9218619835333696e-29